// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd6kl5eQ8O1P80bvRN0nEtr713eFSNpc4',
    appId: '1:510826297794:android:2044bc9383b37bb9c67e5b',
    messagingSenderId: '510826297794',
    projectId: 'sgp-helping-hands',
    storageBucket: 'sgp-helping-hands.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-z5-I3OMXbujyotyCyh2Y9wdhUOYxgFI',
    appId: '1:510826297794:ios:446e5f945645ca68c67e5b',
    messagingSenderId: '510826297794',
    projectId: 'sgp-helping-hands',
    storageBucket: 'sgp-helping-hands.appspot.com',
    androidClientId: '510826297794-o7sssn5so9admlirjelton9rnb328pjp.apps.googleusercontent.com',
    iosClientId: '510826297794-vh5pf08qc0in1avmihg7muun4qhnmvv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );
}
